drop table if exists notes;
drop table if exists folders;

create table folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folders_name TEXT NOT NULL
);


create table notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  notes_name TEXT NOT NULL,
  content TEXT NOT NULL,
  modified date default now(),
  folders_id INTEGER NOT NULL REFERENCES folders(id) ON DELETE CASCADE
);